---
version: '3.8'
services:
  shiori:
    image: pyunramura/shiori:latest
    container_name: Shiori
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - shiori_data:/srv/shiori
volumes:
  shiori_data:
